<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="Krosoft.Extensions.Testing" Version="2026.9.13.10580" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.12" />
		<PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.12" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\src\Krosoft.Extensions.Observability\Krosoft.Extensions.Observability.csproj" />
	</ItemGroup>
	<ItemGroup>
		<None Update="appsettings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>
